name: Build docker

on:
  pull_request:
  push:
    branches: ["*"]
    tags-ignore:
      - build-*
  workflow_dispatch:
    inputs:
      increaseVersion:
        description: "Increase version - yes/no"
        default: "yes"
        required: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: build:
        run: docker build -t test:test .
        
        
      - name: Manifest Generation
        run: |
          curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
          billy generate \
              --access-token "${{ secrets.GITHUB_TOKEN }}" \
              --aqua-key "${{ secrets.AQUA_KEY }}" \
              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
              --artifact-path "test:test"
